import content, {type Experience} from '../content/portfolio';
export function ExperienceCards({items}:{items:Experience[]}){return <div className="cv-grid">{items.map((item,index)=><article className="cv-card" key={`${item.organization}-${index}`}><div className="experience-meta"><span>{item.organization}</span><span>{item.date}</span></div><h3>{item.title}</h3><p>{item.description}</p>{!!item.details?.length && <ul>{item.details.map(detail=><li key={detail}>{detail}</li>)}</ul>}</article>)}</div>}
export function CVSections({section}:{section:string}){const {settings,experience,leadership,education,awards,skills}=content;return <>
  {section==="experience"&&<section id="experience" className="cv-section wrap" aria-labelledby="experience-title"><div className="section-heading"><div><p className="eyebrow">{settings.experience.eyebrow}</p><h2 id="experience-title">{settings.experience.title}</h2></div></div><ExperienceCards items={experience}/></section>}
  {section==="leadership"&&<section id="leadership" className="leadership-section" aria-labelledby="leadership-title"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">{settings.leadership.eyebrow}</p><h2 id="leadership-title">{settings.leadership.title}</h2></div></div><ExperienceCards items={leadership}/></div></section>}
  {section==="education"&&<section id="education" className="cv-section wrap" aria-labelledby="education-title"><div className="section-heading"><div><p className="eyebrow">{settings.education.eyebrow}</p><h2 id="education-title">{settings.education.title}</h2></div></div><div className="education-layout"><article className="education-card"><p className="eyebrow">{education.date}</p><h3>{education.degree}</h3><p>{education.school}</p>{education.gpa&&<strong>{settings.education.gpaLabel} {education.gpa}</strong>}<p>{education.coursework}</p></article>{education.previous?.map(item=><article className="education-card" key={item.degree}><p className="eyebrow">{item.date}</p><h3>{item.degree}</h3><p>{item.school}</p>{item.details?.map(detail=><p key={detail}>{detail}</p>)}</article>)}</div></section>}
  {section==="awards"&&<section id="awards" className="cv-section wrap" aria-labelledby="awards-title"><div className="section-heading"><div><p className="eyebrow">{settings.awards.eyebrow}</p><h2 id="awards-title">{settings.awards.title}</h2></div></div><div className="awards-grid">{awards.map((award,index)=><article className="award-card" key={index}><p className="eyebrow">{award.date}</p><h3>{award.title}</h3><p>{award.organization}</p></article>)}</div></section>}
  {section==="skills"&&<section id="skills" className="skills-section wrap" aria-labelledby="skills-title"><div><p className="eyebrow">{settings.skills.eyebrow}</p><h2 id="skills-title">{settings.skills.title}</h2></div><div className="skills-grid">{skills.map(group=><div key={group.title}><h3>{group.title}</h3><ul>{group.items.map(item=><li key={item}>{item}</li>)}</ul></div>)}</div></section>}
  </>}
