import content, {type Experience} from '../content/portfolio';
export function ExperienceCards({items}:{items:Experience[]}){return <div className="cv-grid">{items.map((item,index)=><article className="cv-card" key={`${item.organization}-${index}`}><div className="experience-meta"><span>{item.organization}</span><span>{item.date}</span></div><h3>{item.title}</h3><p>{item.description}</p>{!!item.details?.length && <ul>{item.details.map(detail=><li key={detail}>{detail}</li>)}</ul>}</article>)}</div>}
export function CVSections(){const {profile,experience,leadership,education,awards,skills}=content;return <>
  <section id="about" className="about-section"><div className="wrap about-overview"><div><p className="eyebrow">02 / ABOUT</p><h2>From CAD<br/>to the cockpit.</h2></div><div><p>{profile.about}</p><p className="professional-summary">{profile.summary}</p><div className="language-list">{profile.languages?.map(item=><span key={item.language}>{item.language} · {item.level}</span>)}</div></div></div></section>
  <section id="experience" className="cv-section wrap" aria-labelledby="experience-title"><div className="section-heading"><div><p className="eyebrow">03 / TECHNICAL EXPERIENCE</p><h2 id="experience-title">Across engineering disciplines.</h2></div></div><ExperienceCards items={experience}/></section>
  <section id="leadership" className="leadership-section" aria-labelledby="leadership-title"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">04 / LEADERSHIP & COMMUNITY</p><h2 id="leadership-title">Working with people.</h2></div></div><ExperienceCards items={leadership}/></div></section>
  <section id="education" className="cv-section wrap" aria-labelledby="education-title"><div className="section-heading"><div><p className="eyebrow">05 / EDUCATION & RECOGNITION</p><h2 id="education-title">A foundation to build on.</h2></div></div><div className="education-layout"><div><article className="education-card"><p className="eyebrow">{education.date}</p><h3>{education.degree}</h3><p>{education.school}</p><strong>GPA {education.gpa}</strong><p>{education.coursework}</p></article>{education.previous?.map(item=><article className="education-card" key={item.degree}><p className="eyebrow">{item.date}</p><h3>{item.degree}</h3><p>{item.school}</p>{item.details?.map(detail=><p key={detail}>{detail}</p>)}</article>)}</div><div className="awards-list"><h3>Awards & achievements</h3>{awards.map((award,index)=><article key={index}><p className="eyebrow">{award.date}</p><h4>{award.title}</h4><p>{award.organization}</p></article>)}</div></div></section>
  <section id="skills" className="skills-section wrap" aria-labelledby="skills-title"><div><p className="eyebrow">06 / TECHNICAL COMPETENCIES</p><h2 id="skills-title">Tools I work with.</h2></div><div className="skills-grid">{skills.map(group=><div key={group.title}><h3>{group.title}</h3><ul>{group.items.map(item=><li key={item}>{item}</li>)}</ul></div>)}</div></section>
  </>}
