import content,{type Experience} from '../content/portfolio';
import {asset} from '../lib/paths';
import {OrganizationMark} from './page-intro';
export function ExperienceCards({items}:{items:Experience[]}){return <div className="timeline">{items.map((item,i)=><article className="timeline-entry" key={i}><div className="timeline-meta"><p className="eyebrow">{item.date}</p><OrganizationMark name={item.organization}/><p>{item.organization}</p></div><div><h2>{item.title}</h2><p className="entry-summary">{item.description}</p>{!!item.details?.length&&<ul>{item.details.map((d,j)=><li key={j}>{d}</li>)}</ul>}{item.image&&<figure className="entry-photo"><img src={asset(item.image)} alt={item.imageAlt||''} loading="lazy" width="1200" height="800"/>{item.imageCaption&&<figcaption>{item.imageCaption}</figcaption>}</figure>}</div></article>)}</div>}
export function CVSections({section}:{section:string}){const {education,awards,skills,settings}=content;return <div className="page-body wrap">
{section==='experience'&&<ExperienceCards items={content.experience}/>}
{section==='leadership'&&<ExperienceCards items={content.leadership}/>}
{section==='education'&&<div className="timeline"><article className="timeline-entry"><div className="timeline-meta"><p className="eyebrow">{education.date}</p><OrganizationMark name={education.school}/></div><div><h2>{education.degree}</h2><p className="entry-summary">{education.school}</p>{education.gpa&&<p className="gpa">{settings.education.gpaLabel} <strong>{education.gpa}</strong></p>}<p>{education.coursework}</p></div></article>{education.previous?.map((e,i)=><article className="timeline-entry" key={i}><p className="eyebrow">{e.date}</p><div><h2>{e.degree}</h2><p className="entry-summary">{e.school}</p>{e.details?.map((d,j)=><p key={j}>{d}</p>)}</div></article>)}</div>}
{section==='awards'&&<div className="timeline">{awards.map((a,i)=><article className="timeline-entry" key={i}><div className="timeline-meta"><p className="eyebrow">{a.date}</p><OrganizationMark name={a.organization}/></div><div><h2>{a.title}</h2><p className="entry-summary">{a.organization}</p></div></article>)}</div>}
{section==='skills'&&<><div className="skill-legend"><span className="eyebrow">{settings.skills.legend}</span><span>{settings.skills.levels.slice(1).join(' / ')}</span></div><div className="skill-categories">{skills.map((group,i)=><section className="skill-category" key={i}><div><span className="eyebrow">{String(i+1).padStart(2,'0')}</span><h2>{group.title}</h2></div><ul>{group.items.map((skill,j)=>{const level=Math.min(4,Math.max(0,Number(skill.level)||0));return <li key={j}><div className="skill-name"><strong>{skill.name}</strong>{skill.note&&<small>{skill.note}</small>}</div><div className="skill-rating"><span>{settings.skills.levels[level]}</span><div className={`skill-meter ${level?'':'unrated'}`} aria-hidden="true">{[1,2,3,4].map(n=><i key={n} className={n<=level?'filled':''}/>)}</div></div></li>})}</ul></section>)}</div></>}
</div>}
