import {Picture} from './picture';
import {ArrowRight,ArrowLeft,ArrowUpRight} from 'lucide-react';
import content,{type Project} from '../content/portfolio';
import {asset,pageUrl,projectUrl} from '../lib/paths';
import {PageBlocks,StoryBlocks,Video} from './story-blocks';
import {Header,Footer} from './site-chrome';
import {PageIntro,OrganizationMark,safeWebUrl} from './page-intro';
const labels=content.settings.work;
const orderedProjects=()=>[...content.projects.filter(p=>p.featured!==false),...content.projects.filter(p=>p.featured===false)];
export function ProjectImage({project}:{project:Project}){const image=project.cover||project.images[0]?.src;return image?<figure className="project-visual"><Picture layout={project.cover?project.coverLayout:project.images[0]?.srcLayout} src={asset(image)} alt={project.cover?project.coverAlt||'':project.images[0]?.alt||''} width="1200" height="600" loading="lazy" style={{objectFit:project.coverFit==='cover'?'cover':'contain',objectPosition:project.coverPosition||'center'}}/>{project.coverCaption&&project.cover&&<figcaption>{project.coverCaption}</figcaption>}</figure>:null}
export function ProjectsPage(){const items=orderedProjects();return <><Header page="work"/><main id="main"><PageIntro page="work" eyebrow={labels.eyebrow} title={labels.title} description={labels.description}/><div className={`project-index wrap project-layout-${content.settings.appearance.projectLayout}`}>{items.map((p,i)=><article className={`project-row ${p.cover||p.images.length?'':'no-visual'}`} key={p.id}><a className="project-image-link" href={projectUrl(p.id)} aria-label={`${labels.caseStudyLabel}: ${p.title}`}><ProjectImage project={p}/></a><div className="project-row-copy"><p className="eyebrow">{String(i+1).padStart(2,'0')} / {p.category}</p><h2><a href={projectUrl(p.id)}>{p.title}</a></h2><p className="project-organization">{p.organization}</p><p>{p.summary}</p><ul className="tags">{p.tools.map(t=><li key={t}>{t}</li>)}</ul><a className="text-link" href={projectUrl(p.id)}>{labels.caseStudyLabel}<ArrowRight size={20}/></a></div></article>)}</div><PageBlocks page="work"/></main><Footer/></>}
export function ProjectPage({project:p}:{project:Project}){const projects=orderedProjects();const index=projects.findIndex(x=>x.id===p.id);const next=projects[(index+1)%projects.length];return <><Header page="work"/><main id="main" className="case-study"><div className="wrap case-heading"><a className="text-link" href={pageUrl('work')}><ArrowLeft size={16}/>{labels.backLabel}</a><p className="eyebrow">{p.category}</p><h1>{p.title}</h1><p className="case-summary">{p.summary}</p></div><div className="wrap"><ProjectImage project={p}/><dl className="project-facts"><div><dt>{labels.roleLabel}</dt><dd>{p.role}</dd></div><div><dt>{labels.organizationLabel}</dt><dd>{p.organization}<OrganizationMark name={p.organization} visible={p.showLogo} logo={p.logo} layout={p.logoLayout}/></dd></div><div><dt>{labels.dateLabel}</dt><dd>{p.date}</dd></div></dl><section className="case-contribution"><h2>{labels.contributionLabel}</h2><div><ul>{p.contributions.map((c,i)=><li key={i}>{c}</li>)}</ul><div className="case-outcome"><p className="eyebrow">{p.outcomeLabel}</p><p>{p.outcome}</p></div><ul className="tags" aria-label={labels.toolsLabel}>{p.tools.map(t=><li key={t}>{t}</li>)}</ul></div></section><StoryBlocks blocks={p.sections} label={labels.storyLabel}/>{(p.images.length>0||p.videos.length>0)&&<section className="project-media"><h2>{labels.mediaLabel}</h2><div className="project-media-grid">{p.images.map((img,i)=><figure key={i}><Picture layout={img.srcLayout} src={asset(img.src)} alt={img.alt} width="1200" height="800" loading="lazy"/>{img.caption&&<figcaption>{img.caption}</figcaption>}</figure>)}</div>{p.videos.map((v,i)=><div key={i}><h3>{v.title}</h3><Video url={v.url} file={v.file} title={v.title} caption={v.caption} captions={v.captions} captionLanguage={v.captionLanguage} captionLabel={v.captionLabel}/></div>)}</section>}{safeWebUrl(p.link)&&<a className="text-link" href={safeWebUrl(p.link)} target="_blank" rel="noreferrer">{labels.linkLabel}<ArrowUpRight size={16}/></a>}{next&&next.id!==p.id&&<a className="next-project" href={projectUrl(next.id)}><span><small>{labels.nextLabel}</small>{next.title}</span><ArrowRight/></a>}</div></main><Footer/></>}
