import Markdown,{defaultUrlTransform} from 'react-markdown';
import {ArrowRight,ArrowLeft,ArrowUpRight} from 'lucide-react';
import content,{type Project} from '../content/portfolio';
import {asset,pageUrl,projectUrl} from '../lib/paths';
import {embedUrl} from '../lib/media';
import {Header,Footer} from './site-chrome';
import {PageIntro,OrganizationMark,safeWebUrl} from './page-intro';
const labels=content.settings.work;
const orderedProjects=()=>[...content.projects.filter(p=>p.featured!==false),...content.projects.filter(p=>p.featured===false)];
export function ProjectImage({project}:{project:Project}){const image=project.cover||project.images[0]?.src;return image?<figure className="project-visual"><img src={asset(image)} alt={project.cover?project.coverAlt||'':project.images[0]?.alt||''} width="1200" height="600" loading="lazy"/>{project.coverCaption&&project.cover&&<figcaption>{project.coverCaption}</figcaption>}</figure>:null}
export function Video({url,file,title,caption}:{url?:string;file?:string;title:string;caption?:string}){const embed=embedUrl(url);return file||embed?<figure className="video-figure">{file?<video controls playsInline preload="metadata" aria-label={title} src={asset(file)}/>:<iframe src={embed} title={title} loading="lazy" allow="fullscreen; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>}{caption&&<figcaption>{caption}</figcaption>}</figure>:null}
export function ProjectsPage(){const items=orderedProjects();return <><Header page="work"/><main id="main"><PageIntro page="work" eyebrow={labels.eyebrow} title={labels.title} description={labels.description}/><div className="project-index wrap">{items.map((p,i)=><article className={`project-row ${p.cover||p.images.length?'':'no-visual'}`} key={p.id}><a className="project-image-link" href={projectUrl(p.id)} aria-label={`${labels.caseStudyLabel}: ${p.title}`}><ProjectImage project={p}/></a><div className="project-row-copy"><p className="eyebrow">{String(i+1).padStart(2,'0')} / {p.category}</p><h2><a href={projectUrl(p.id)}>{p.title}</a></h2><p className="project-organization">{p.organization}</p><p>{p.summary}</p><ul className="tags">{p.tools.map(t=><li key={t}>{t}</li>)}</ul><a className="text-link" href={projectUrl(p.id)}>{labels.caseStudyLabel}<ArrowRight size={20}/></a></div></article>)}</div></main><Footer/></>}
export function ProjectPage({project:p}:{project:Project}){const projects=orderedProjects();const index=projects.findIndex(x=>x.id===p.id);const next=projects[(index+1)%projects.length];return <><Header page="work"/><main id="main" className="case-study"><div className="wrap case-heading"><a className="text-link" href={pageUrl('work')}><ArrowLeft size={16}/>{labels.backLabel}</a><p className="eyebrow">{p.category}</p><h1>{p.title}</h1><p className="case-summary">{p.summary}</p></div><div className="wrap"><ProjectImage project={p}/><dl className="project-facts"><div><dt>{labels.roleLabel}</dt><dd>{p.role}</dd></div><div><dt>{labels.organizationLabel}</dt><dd>{p.organization}<OrganizationMark name={p.organization}/></dd></div><div><dt>{labels.dateLabel}</dt><dd>{p.date}</dd></div></dl><section className="case-contribution"><h2>{labels.contributionLabel}</h2><div><ul>{p.contributions.map((c,i)=><li key={i}>{c}</li>)}</ul><div className="case-outcome"><p className="eyebrow">{p.outcomeLabel}</p><p>{p.outcome}</p></div><ul className="tags" aria-label={labels.toolsLabel}>{p.tools.map(t=><li key={t}>{t}</li>)}</ul></div></section><div className="story-blocks">{p.sections.map((s,i)=><section key={i} className={`story-block ${['image-left','image-right','full'].includes(s.layout||'')?s.layout:'full'}`}><div className="story-copy"><p className="eyebrow">{labels.storyLabel} / {String(i+1).padStart(2,'0')}</p><h2>{s.title}</h2>{s.body&&<div className="post-body"><Markdown skipHtml urlTransform={url=>/^\/?assets\//.test(url)?asset(url):defaultUrlTransform(url)}>{s.body}</Markdown></div>}</div>{s.image&&<figure><img src={asset(s.image)} alt={s.imageAlt||''} width="1200" height="800" loading="lazy"/>{s.caption&&<figcaption>{s.caption}</figcaption>}</figure>}<Video url={s.videoUrl} file={s.videoFile} title={s.title}/></section>)}</div>{(p.images.length>0||p.videos.length>0)&&<section className="project-media"><h2>{labels.mediaLabel}</h2><div className="project-media-grid">{p.images.map((img,i)=><figure key={i}><img src={asset(img.src)} alt={img.alt} width="1200" height="800" loading="lazy"/>{img.caption&&<figcaption>{img.caption}</figcaption>}</figure>)}</div>{p.videos.map((v,i)=><div key={i}><h3>{v.title}</h3><Video url={v.url} file={v.file} title={v.title} caption={v.caption}/></div>)}</section>}{safeWebUrl(p.link)&&<a className="text-link" href={safeWebUrl(p.link)} target="_blank" rel="noreferrer">{labels.linkLabel}<ArrowUpRight size={16}/></a>}{next&&next.id!==p.id&&<a className="next-project" href={projectUrl(next.id)}><span><small>{labels.nextLabel}</small>{next.title}</span><ArrowRight/></a>}</div></main><Footer/></>}
