import content from '../content/portfolio';
import {asset,homeUrl,pageUrl,routeIds} from '../lib/paths';
export function Header({page='intro'}:{page?:string}) {
  const {settings,profile}=content;
  const items=settings.navigation.filter(item=>routeIds.includes(item.target as typeof routeIds[number])&&settings.sections.includes(item.target));
  const link=(item:typeof items[number],index:number)=><a key={index} href={pageUrl(item.target)} aria-current={item.target===page?'page':undefined}>{item.label}</a>;
  return <><a className="skip-link" href="#main">{settings.accessibility.skipLink}</a><div className="header-shell"><header className="site-header wrap"><a className="wordmark" href={homeUrl} aria-label={`${profile.name}, ${settings.accessibility.home}`}><>{settings.branding.logo?<img className="brand-logo" src={asset(settings.branding.logo)} alt="" width="48" height="48"/>:<span className="monogram">{settings.branding.monogram}</span>}{settings.branding.showName&&<span>{profile.name}<br/><span className="wordmark-sub">{settings.branding.subtitle}</span></span>}</></a><nav aria-label={settings.accessibility.navigation}>{items.filter(i=>i.placement!=='more').map(link)}{items.some(i=>i.placement==='more')&&<details className="nav-more"><summary>{settings.branding.moreLabel}<span className="nav-toggle-icon" aria-hidden="true"/></summary><div className="nav-menu">{items.filter(i=>i.placement==='more').map(link)}</div></details>}</nav></header></div></>;
}
export function Footer(){const b=content.settings.branding;if(!b.showFooter)return null;const copyright=(b.copyright??'').replaceAll('{year}',String(new Date().getFullYear())).replaceAll('{name}',content.profile.name);return <footer className="wrap">{copyright&&<span>&copy; {copyright}</span>}<span>{b.footer}</span>{b.showBackToTop&&<a href="#main">{content.settings.accessibility.backToTop}</a>}</footer>}
