import Markdown,{defaultUrlTransform} from 'react-markdown';
import {ArrowUpRight,ArrowLeft,ArrowRight} from 'lucide-react';
import {Header,Footer} from './site-chrome';
import content from '../content/portfolio';
import {type Post} from '../lib/posts';
import {asset,updatesUrl} from '../lib/paths';
const dateLabel=(date:string)=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`));
export function UpdatesIndex({posts}:{posts:Post[]}){return <><Header updates/><main id="main" className="wrap updates-main"><div className="updates-heading"><p className="eyebrow">ENGINEERING UPDATES</p><h1>Notes along<br/><span>the way.</span></h1><p>Project progress, lessons from building, and life as an aerospace engineering student.</p></div><div className="updates-layout"><div className="post-feed">{posts.length?posts.map(post=><article className="post-preview" key={post.slug}><div className="post-byline"><span className="author-avatar" aria-hidden="true">SM</span><div><strong>{content.profile.name}</strong><time dateTime={post.date}>{dateLabel(post.date)}</time></div></div><h2><a href={`${updatesUrl}${post.slug}/`}>{post.title}</a></h2>{post.excerpt&&<p>{post.excerpt}</p>}{post.image&&<a href={`${updatesUrl}${post.slug}/`} tabIndex={-1} aria-hidden="true"><img src={asset(post.image)} alt="" width="1200" height="800" loading="lazy"/></a>}<a className="text-link" href={`${updatesUrl}${post.slug}/`}>Read update <ArrowRight size={17}/></a></article>):<div className="empty-updates"><span className="eyebrow">THE JOURNAL</span><h2>Updates are on the way.</h2><p>This is where I’ll share what I’m building, testing, and learning.</p></div>}</div><aside className="updates-aside"><p className="eyebrow">BEHIND THE WORK</p><h2>{content.profile.firstName}<br/>{content.profile.lastName}</h2><p>{content.profile.role}</p><a className="text-link" href={content.profile.linkedin} target="_blank" rel="noreferrer">Connect on LinkedIn <ArrowUpRight size={16}/></a></aside></div></main><Footer/></>}
export function PostPage({post}:{post:Post}){return <><Header updates/><main id="main" className="wrap article-main"><a className="text-link" href={updatesUrl}><ArrowLeft size={17}/> All updates</a><article className="post-article"><p className="eyebrow">ENGINEERING UPDATES · <time dateTime={post.date}>{dateLabel(post.date)}</time></p><h1>{post.title}</h1><p className="article-author">By {content.profile.name}</p>{post.image&&<img className="article-cover" src={asset(post.image)} alt={post.imageAlt||''} width="1200" height="800"/>}<div className="post-body"><Markdown skipHtml urlTransform={(url)=>/^\/?assets\//.test(url)?asset(url):defaultUrlTransform(url)} components={{img:({src,alt})=><img src={src} alt={alt||''} loading="lazy"/>,a:({href,children})=><a href={href}>{children}</a>}}>{post.body}</Markdown></div>{post.linkedin&&<a className="button primary" href={post.linkedin} target="_blank" rel="noreferrer">Read on LinkedIn <ArrowUpRight size={17}/></a>}</article></main><Footer/></>}
