import Markdown,{defaultUrlTransform} from 'react-markdown';
import {ArrowUpRight,ArrowLeft,ArrowRight} from 'lucide-react';
import {contactHref} from './contact';
import {Header,Footer} from './site-chrome';
import {PageIntro} from './page-intro';
import content from '../content/portfolio';
import {type Post} from '../lib/posts';
import {asset,updatesUrl} from '../lib/paths';
const {journal}=content.settings;
const dateLabel=(date:string)=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`));
export function UpdatesIndex({posts}:{posts:Post[]}){const linkedin=content.contact.links.find(link=>link.type==='linkedin');return <><Header page="updates"/><main id="main" className="updates-main"><PageIntro page="updates" eyebrow={journal.eyebrow} title={journal.title} description={journal.description}/><div className="updates-layout wrap"><div className="post-feed">{posts.length?posts.map(post=><article className="post-preview" key={post.slug}><div className="post-byline"><span className="author-avatar" aria-hidden="true">{content.settings.branding.monogram}</span><div><strong>{content.profile.name}</strong><time dateTime={post.date}>{dateLabel(post.date)}</time></div></div><h2><a href={`${updatesUrl}${post.slug}/`}>{post.title}</a></h2>{post.excerpt&&<p>{post.excerpt}</p>}{post.image&&<a href={`${updatesUrl}${post.slug}/`} tabIndex={-1} aria-hidden="true"><img src={asset(post.image)} alt="" width="1200" height="800" loading="lazy"/></a>}<a className="text-link" href={`${updatesUrl}${post.slug}/`}>{journal.readLabel}<ArrowRight size={17}/></a></article>):<div className="empty-updates"><span className="eyebrow">{journal.emptyEyebrow}</span><h2>{journal.emptyTitle}</h2><p>{journal.emptyDescription}</p></div>}</div><aside className="updates-aside"><p className="eyebrow">{journal.asideLabel}</p><h2>{content.profile.name}</h2><p>{content.profile.role}</p>{linkedin&&<a className="text-link" href={contactHref(linkedin!)} target="_blank" rel="noreferrer">{journal.connectLabel}<ArrowUpRight size={16}/></a>}</aside></div></main><Footer/></>}
export function PostPage({post}:{post:Post}){return <><Header page="updates"/><main id="main" className="wrap article-main"><a className="text-link" href={updatesUrl}><ArrowLeft size={17}/>{journal.backLabel}</a><article className="post-article"><p className="eyebrow">{journal.eyebrow} {'\u00b7'} <time dateTime={post.date}>{dateLabel(post.date)}</time></p><h1>{post.title}</h1><p className="article-author">{journal.byLabel} {content.profile.name}</p>{post.image&&<img className="article-cover" src={asset(post.image)} alt={post.imageAlt||''} width="1200" height="800"/>}<div className="post-body"><Markdown skipHtml urlTransform={(url)=>/^\/?assets\//.test(url)?asset(url):defaultUrlTransform(url)} components={{img:({src,alt})=><img src={src} alt={alt||''} loading="lazy"/>,a:({href,children})=><a href={href}>{children}</a>}}>{post.body}</Markdown></div>{post.linkedin&&<a className="button primary" href={post.linkedin} target="_blank" rel="noreferrer">{journal.linkedinLabel}<ArrowUpRight size={17}/></a>}</article></main><Footer/></>}
