import {ArrowRight,ArrowUpRight} from 'lucide-react';
import content from '../content/portfolio';
import {IntroPhotos} from '../components/intro-photos';
import {Header,Footer} from '../components/site-chrome';
import {PageBlocks} from '../components/story-blocks';
import {Cover} from '../components/page-intro';
import {asset,pageUrl} from '../lib/paths';
export const dynamic = 'force-static';
export default function Home(){const {profile,settings}=content;const home=settings.home;const names=profile.name.split(/\s+/);return <><Header/><main id="main"><Cover page="intro"/><section id="intro" className={`hero wrap photo-${home.photoSide} ${content.introPhotos.visible&&content.introPhotos.photos.length?'hero-with-photos':'hero-simple'}`}><div className="hero-copy">{home.showAvailability&&<p className="eyebrow"><span className="status-dot"/>{profile.availability}</p>}<h1>{home.nameLayout==='inline'?profile.name:<>{names[0]}<br/><span>{names.slice(1).join(' ')}</span></>}</h1><p className="hero-role">{profile.role}</p><div className="hero-intro">{profile.intro.split(/\n\s*\n/).filter(Boolean).map((p,i)=><p className="preserve-lines" key={i}>{p}</p>)}</div>{home.showLanguages&&<div className="language-list">{profile.languages?.map(l=><span key={l.language}>{l.language} {'\u00b7'} {l.level}</span>)}</div>}<div className="hero-actions">{home.showWorkButton&&settings.sections.includes('work')&&<a className="button primary" href={pageUrl('work')}>{settings.intro.workButton}<ArrowRight size={18}/></a>}{home.showCvButton&&<a className="text-link" href={asset(content.contact.resume)} target="_blank" rel="noreferrer">{settings.intro.cvButton}<ArrowUpRight size={18}/></a>}</div></div><IntroPhotos/></section>{home.showHighlights&&!!profile.highlights.length&&<div className="credentials wrap">{profile.highlights.map((h,i)=><div key={i}><strong>{h.value}</strong><span>{h.label}</span></div>)}</div>}{home.showDirectory&&<section className="portfolio-directory wrap"><div className="section-heading"><h2>{settings.intro.exploreLabel}</h2><p>{settings.intro.exploreDescription}</p></div><div>{settings.navigation.filter(n=>n.target!=='intro'&&settings.sections.includes(n.target)).map((n,i)=><a href={pageUrl(n.target)} key={i}><span className="directory-number">{String(i+1).padStart(2,'0')}</span><span>{n.label}</span><ArrowRight size={24}/></a>)}</div></section>}<PageBlocks page="intro"/></main><Footer/></>}
